### ISSUE TITLE
서버 구현 및 AWS 연동

### ISSUE THREAD

**Issue by ldh-dodo** [CloudComputingJBNU/Group-Buying-Community-App#16]
## To-do
 - [x] 회원가입시 유저 정보 insert
 - [x] 카테고리 label 가져오기
 - [x] 게시글 추가 
 - [x] 카테고리 정보로 게시글 정보 가져오기
 - [x] 마이페이지 유저 수정
